### ISSUE TITLE
`nix-user-chroot ~/.nix bash` does not have nix in $PATH

### ISSUE THREAD

**Issue by EggBaconAndSpam** [nix-community/nix-user-chroot#12]
Nix sets itself up in `~/.bash_profile`, which is only sourced by 'login' shells. Since outside the chroot the symlink `~/.nix-profile` doesn't point to anything, the nix executables are never added to $PATH, i.e. `nix`/`nix-shell` etc don't show up.

My solution is to run `nix-user-chroot ~/.nix bash -l`, which tells bash to source `~/.bash_profile` again inside the chroot.

Has anyone else faced this issue, or did I mess up something else along the way?

**Comment by worldofgeese** [comment]
I have this same issue.

**Comment by Mic92** [comment]
How about adding the same lines to `$HOME/.bashrc` than?

**Comment by Mic92** [comment]
Otherwise I just change the documentation to include `-l`.

**Comment by senorsmile** [comment]
I have the same problem (on current Manjaro): 

```
$ ./nix-user-chroot-bin-1.2.1-x86_64-unknown-linux-musl ~/.nix bash -c "curl -L https://nixos.org/nix/install | bash"
...
Installation finished!  To ensure that the necessary environment
variables are set, either log in again, or type

  . /home/senorsmile/.nix-profile/etc/profile.d/nix.sh

in your shell.
```

```
$ . /home/senorsmile/.nix-profile/etc/profile.d/nix.sh
bash: /home/senorsmile/.nix-profile/etc/profile.d/nix.sh: No such file or directory
```

```
$ ls -alh ~/.nix-profile
lrwxrwxrwx 1 senorsmile senorsmile 46 May  1 07:30 /home/senorsmile/.nix-profile -> /nix/var/nix/profiles/per-user/senorsmile/profile
```

**Comment by Mic92** [comment]
@senorsmile you need to run `./nix-user-chroot-bin-1.2.1-x86_64-unknown-linux-musl ~/.nix bash -l` again after installing nix to get a shell with nix installed.

**Comment by senorsmile** [comment]
Oh, that makes sense now.  I thought that was a way to call it manually, but that's the only way to activate it.    Therefore I don't have the same issue.
