### ISSUE TITLE
"No user exists for uid" when using `git push`

### ISSUE THREAD

**Issue by Nadrieril** [nix-community/nix-user-chroot#15]
When I run `git push -v` from within `nix-user-chroot`, I get the following error:
```
Pushing to git@github.com:Nadrieril/rust
No user exists for uid 12725
fatal: Could not read from remote repository.
```
This specifically occurs for ssh remotes. http remotes work fine. Weirdly `ssh` itself seems to work fine.

For context, this is a managed workstation running Fedora 30, and my user is virtual. From what I understand, because `nix-user-chroot` creates a new user namespace, NSS cannot find info about my user. I understand there might be workarounds possible involving `libnss_wrapper` but I'm not familiar with the details of either NSS or user namespaces.
Is this something that could be fixed by `nix-user-chroot` ? Actually, out of curiosity, why does `nix-user-chroot` create a user namespace ? I would have imagined that a mount namespace would be sufficient.
EDIT: ok I understand why: `CLONE_NEWNS` needs `CAP_SYS_ADMIN`, so you need `CLONE_NEWUSER` too to get that.

**Comment by Mic92** [comment]
Yes. the whole point of this tool is not to need root. It is weird though, that `nix-user-chroot` leads to a changed uid. Actually we map the original uid into the usernamespace: https://github.com/nix-community/nix-user-chroot/blob/master/src/main.rs#L165

**Comment by Nadrieril** [comment]
The uid is not changed, `12725` is my original uid.
I've done some investigation, and it turns out the problem is specific to nss: `getent passwd` wasn't listing my user. And turns out that my user was defined by `sssd`, and `getent` couldn't find the required `libnss_sss.so.2`. Using `LD_PRELOAD=/usr/lib64/libnss_sss.so.2` fixed the problem. So it was a nix issue after all ><
