### ISSUE TITLE
thread 'main' panicked at 'unshare failed: Sys(EINVAL)', src/main.rs:97:5

### ISSUE THREAD

**Issue by Munksgaard** [nix-community/nix-user-chroot#19]
I'm guessing this is related to #10, but in case it is not (the error message is slightly different, after all) here is the output when I run nix-user-chroot:

```
$ RUST_BACKTRACE=1  ./nix-user-chroot-bin-1.0.3-x86_64-unknown-linux-musl ~/.nix bash
thread 'main' panicked at 'unshare failed: Sys(EINVAL)', src/main.rs:97:5
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'failed to remove temporary directory: /tmp/.tmpitsGGH', src/main.rs:200:21
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

And it seems like namespaces are allowed by the kernel, although as you mention, they may have been disabled at a later stage.

```
$ grep CONFIG_USER_NS /boot/config-$(uname -r)
CONFIG_USER_NS=y
```

**Comment by Mic92** [comment]
What is your Linux distribution? At least redhat and debian have runtime option to disable usernamespaces again.

**Comment by Munksgaard** [comment]
It's an old RHEL I think. It's a shared server with very old software on it that I don't have root access to, and I'm trying to use Nix to avoid having to manually recompile _everything_.

**Comment by Munksgaard** [comment]
For reference, this is what I get when I try to run `ushare`:

```
$ unshare --user --pid
unshare: unshare failed: Invalid argument
```

**Comment by Mic92** [comment]
Yeah. You need at Linux 3.8 for this tool to work. As alternative you may re-compile nix with a different store paths or have a look at guix pack relocatable: https://guix.gnu.org/manual/devel/en/html_node/Invoking-guix-pack.html

**Comment by Munksgaard** [comment]
Now that I take a look, I'm actually on 3.10:

```
$ uname -a
Linux a00333.science.domain 3.10.0-1127.18.2.el7.x86_64 #1 SMP Mon Jul 20 22:32:16 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

However, I think you may be right that user namespaces have been disabled.

**Comment by stites** [comment]
I am getting this same bug on Centos 7.8, building nix-user-chroot from source with rustup on 9223e3fcb15d7b158e11e57f4c0b793553095e66.

The first two options listed for checking user namespaces fails, but the final option reports:
```
$ grep CONFIG_USER_NS /boot/config-$(uname -r)
CONFIG_USER_NS=y
```

`unshare failed` -- is there a hard dependence on unshare? It doesn't appear to be on this box.

**Comment by stites** [comment]
Okay, more digging. Maybe https://github.com/nix-community/nix-user-chroot/issues/10#issuecomment-516350183 is the problem. I've emailed the IT admins to see if I can confirm this. Thank you!

> It looks like your user is not allowed to call `unshare`, this is quite common on old CentOS and RedHat kernels.
