### ISSUE TITLE
nix-user-chroot causes failure in gnutls init_fds test

### ISSUE THREAD

**Issue by r-burns** [nix-community/nix-user-chroot#20]
Hi, sorry if this is the wrong place for this - just thought I'd point this out here as well in case it turns out to be an issue with the way the chroot is set up.

I've opened an issue (https://gitlab.com/gnutls/gnutls/-/issues/1125) in gnutls, that their init_fds test fails when run inside a nix-user-chroot. The relevant failing part of their test is here: https://gitlab.com/gnutls/gnutls/-/blob/3.6.15/tests/init_fds.c#L56-61

Is their test faulty for making this assumption? Should nix-user-chroot be modified to be more resilient to this type of test? Or is this simply an edge case that should be skipped during checkPhase?

**Comment by Mic92** [comment]
Good question what does `ls -la /proc/self/fd` looks like in this case? Maybe we leak a file descriptor...

**Comment by r-burns** [comment]
Oof, that command pointed out that this is not related to nix-user-chroot at all. The extra entries are actually related to my host OS's `sssd` daemon. Very sorry for the false alarm, closing.
