### ISSUE TITLE
Enhancement: mount /run/opengl-driver/lib for CUDA support

### ISSUE THREAD

**Issue by r-burns** [nix-community/nix-user-chroot#31]
CUDA libraries and applications expect the libcuda.so driver lib to be in /run/opengl-driver/lib, as set by addOpenGLRunpath. If the user can't create /run/opengl-driver/lib/libcuda.so (likely the case if they are using nix-user-chroot) the only way to use CUDA is to use LD_PRELOAD, rebuild all applications with a distro-specific rpath, or mount /run/opengl-driver/lib via some other means.

I think this could be as simple as e.g. checking if nixdir/var/nix/lib exists, and mounting it as /run/opengl-driver/lib. The creation of the /nix/var/nix/lib/libcuda.so -> /some/distro/specific/path/libcuda.so symlink would be left up to the user.

**Comment by Mic92** [comment]
I would merge this, but not implement the feature. In the meantime there is also: https://github.com/guibou/nixGL
