### ISSUE TITLE
Not remapping all users and groups

### ISSUE THREAD

**Issue by NAHFE** [nix-community/nix-user-chroot#42]
When inside the chroot all the other users and group shown as nobody and nogroup.
Sudo also doesn´t work and it says `sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set`.
Ping is not working either. `ping: socket: Operation not permitted`

Any way to fix this problem?

**Comment by Mic92** [comment]
No. As an unprivileged you can map more users but your own. There is the `newuidmap` tool but this requires an administrator to reserve uids for your user account.

**Comment by cebaa** [comment]
@Mic92 Dows that mean there's no way to use `ping` from within `nix-user-chroot`?

**Comment by Mic92** [comment]
No sorry. This is a kernel limitation. This would only work if you root access to create a sandbox that can do that.
