### ISSUE TITLE
Cannot remove `~/.nix`

### ISSUE THREAD

**Issue by tuanpham96** [nix-community/nix-user-chroot#64]
I’m having trouble doing `rm -rf .nix` (created and `chmod 755`) as it continues to say permission denied. I also tried activating the shell first with `nix-user-chroot .nix bash -l` then tried it again, still not working. Even with `chmod 777`, still not working. The other directories/files like `.nix_profile` could be removed however. Any suggestions?

Thanks!

**Comment by Mic92** [comment]
Do you own the directory that contains `.nix`? Since this is a general administration issue not related to `nix-user-chroot`, I am going to close this issue, but continue answer questions.

**Comment by tuanpham96** [comment]
Sorry for the late reply. You're right it's not a `nix-user-chroot` issue. I apologize. I was able to fix it, I just do recursive `chmod -R 777 ~/.nix` and it worked.

**Comment by vale981** [comment]
this should probably be in the documentation
