### ISSUE TITLE
Cannot delete .nix

### ISSUE THREAD

**Issue by NickGeek** [nix-community/nix-user-chroot#85]
Hi,
I installed Nix with nix-user-chroot and I'm wanting to delete my `.nix` directory. The issue is I get permission denied errors when deleting it. I do not have root on this machine so `sudo` is not available to help here.

**Comment by rrbutani** [comment]
Have you tried [running `chmod -R u+w .nix` before trying to delete the directory](https://github.com/DavHau/nix-portable/issues/33#issuecomment-1040617871)? I think `rm -f` doesn't delete directories that don't have the writable bit set.

**Comment by NickGeek** [comment]
That worked! Thanks.
