### ISSUE TITLE
nix-user-chroot crashes

### ISSUE THREAD

**Issue by Luflosi** [nix-community/nix-user-chroot#9]
When I tried to use nix-user-chroot to install nix, it crashed with the following error:
```
$ RUST_BACKTRACE=1 ./nix-user-chroot ~/.nix bash
thread 'main' panicked at 'cannot get stat of /nix/.gvfs', src/main.rs:81:29
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: std::panicking::rust_panic_with_hook
   5: <unknown>
   6: std::panicking::begin_panic_fmt
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: __rust_maybe_catch_panic
  12: std::rt::lang_start_internal
  13: <unknown>
  14: __libc_start_main
  15: <unknown>
```
I tried both the pre-built binaries and building from source.
The machine I tried to install nix on has its home directory on some kind of network share.
I figured, I would just try to ignore that file or directory and came up with the following patch.
These are my very first lines of go code, so keep that in mind.
```diff
diff --git a/src/main.rs b/src/main.rs
index cee77a6..c769912 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -75,6 +75,9 @@ fn bind_mount_direntry(entry: io::Result<fs::DirEntry>) {
     if entry.file_name() == PathBuf::from("nix") {
         return;
     }
+    if entry.file_name() == PathBuf::from(".gvfs") {
+        return;
+    }
     let path = entry.path();
     let stat = entry
         .metadata()
```
This patch fixed my issue but I don't know if it is the right way to fix my issue.

**Comment by Mic92** [comment]
Ignoring directory entries where `.metadata()` fails with a warning message would be a sensible fix. There might be other filesystem mounts or just permission problems that could be worked around this way.

**Comment by Luflosi** [comment]
Feel free to close this issue whenever you want.

**Comment by Mic92** [comment]
No. I think your issue is a valid concern. And having nix-user-chroot to work also in the case of inaccessible resources is useful

**Comment by ariutta** [comment]
I tried using the pre-built binary and am getting two errors (one possibly related to this issue):
>thread 'main' panicked at 'unshare failed: Sys(EPERM)', src/libcore/result.rs:997:5
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
thread 'main' panicked at 'failed to remove temporary directory: /tmp/nix.Q2mICydOk2F0', src/main.rs:200:21
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>

Regarding "'unshare failed", I ran `grep CONFIG_USER_NS /boot/config-$(uname -r)` and got:
>CONFIG_USER_NS=y

Also, I can run `./nix-user-chroot --help` and get this:
>Usage: `./nix-user-chroot <nixpath> <command>`

**Comment by Luflosi** [comment]
Just tested with the latest release and I no longer have this problem. Has this been fixed?

**Comment by Mic92** [comment]
Could be fixed as a side-effect of https://github.com/nix-community/nix-user-chroot/pull/23
