### ISSUE TITLE
Running sudo inside the user-chroot

### ISSUE THREAD

**Issue by traxys** [nix-community/nix-user-chroot#93]
Is there a way to run sudo inside the user-chroot ? I am using the user-chroot not because I don't have admin rights, but because I am using it on a cluster of machines, where I don't want to bind mount /nix on each machine (I go on some machines very rarely). 

They have a shared NFS drive, so I put the chroot root on that NFS. But the problem is that the files like /etc/sudo.conf end up being owned by "nobody" and sudo complains about that. It also complains that the /usr/bin/sudo program is not owned by uid 0 and does not have the setuid bit.

**Comment by Mic92** [comment]
No the way unprivileged usernamespaces work don't allow to `setuid` afterwards. You need to run sudo outside.
