### ISSUE TITLE
ssh does not work inside nix-user-chroot

### ISSUE THREAD

**Issue by jarkkojs** [nix-community/nix-user-chroot#97]
Result:

```
Bad owner or permissions on /etc/ssh/ssh_config.d/50-redhat.conf
```

Other:

```
$ ls -l /etc/ssh/ssh_config.d/
total 4
-rw-r--r-- 1 nobody nobody 831 Jan 21  2022 50-redhat.conf
```

Environment:

* Running fedoraremix inside WSL2.
* nix-user-chroot
* home-manager

Can be worked around by using dbclient from dropbear for common use cases (e.g. ssh logins and git) but e.g. mosh does not play well with it.

**Comment by Mic92** [comment]
The problem here is that all uid's outside of nix-user-chroot are mapped to `nobody`. Since you are using wsl2 can you not install nix normally?
